tap "adoptopenjdk/openjdk"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "microsoft/mssql-release"
tap "mongodb/brew"
tap "wix/brew"
brew "bat"
brew "fd"
brew "fzf"
brew "gist"
brew "go"
brew "htop"
brew "hub"
brew "node"
brew "jsonlint"
brew "mas"
brew "now-cli"
brew "pandoc"
brew "postgresql", restart_service: true
brew "prettier"
brew "rbenv"
brew "redis", restart_service: true
brew "ripgrep"
brew "ruby"
brew "shellcheck"
brew "tldr"
brew "tmate"
brew "todo-txt"
brew "vim"
brew "watchman"
brew "wrk"
brew "yarn"
brew "z"
brew "heroku/brew/heroku"
brew "wix/brew/applesimutils"
cask "adoptopenjdk8"
cask "android-messages"
cask "android-platform-tools"
cask "android-sdk"
cask "android-studio"
cask "appcleaner"
cask "azure-data-studio"
cask "clipy"
cask "disk-drill"
cask "dropbox"
cask "figma"
cask "gimp"
cask "graphql-playground"
cask "kap"
cask "kindle"
cask "lastpass"
cask "ngrok"
cask "popsql"
cask "quik"
cask "react-native-debugger"
cask "slack"
cask "spotify"
cask "tor-browser"
cask "virtualbox"
cask "vlc"
mas "1Password 7", id: 1333542190
mas "Countdowns", id: 926707738
mas "Drafts", id: 1435957248
mas "Grammarly for Safari", id: 1462114288
mas "iMovie", id: 408981434
mas "MindNode", id: 1289197285
